### ISSUE TITLE
Gradianto Dark Fuschia - PHP - background styled green

### ISSUE THREAD

**Issue by Wilkolicious** [thvardhan/Gradianto#25] opened 2020-08-04 09:05 UTC
In the latest update (4.0 or 4.1 I believe), opening up PHP files shows a dark green background which I can only assume comes from Gradianto Nature Green.

As you can see in the screenshot below, the editor color scheme background is being inherited from 'Language Defaults' -> 'Template Language'
<img width="1919" alt="Screenshot 2020-08-04 at 09 56 13" src="https://user-images.githubusercontent.com/16191979/89274681-29bdb580-d639-11ea-8e54-9298363a1183.png">

This is where it's pulling the green background from
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/16191979/89274817-58d42700-d639-11ea-8b2d-510d9113270a.png">

**Comment by thvardhan** [comment] 2020-08-04 10:52
Hi, which IDE is that? I am unable to find a PHP section in IDEA. is that PhpStorm? It should've inherited from a background not template language. I am having the correct background in IDEA. Let me know the IDE so I'll take a look at it 👍 
<img width="1064" alt="Screenshot 2020-08-04 at 4 21 44 PM" src="https://user-images.githubusercontent.com/17314986/89285763-98693600-d66e-11ea-8dae-a90138ae9164.png">

**Comment by Wilkolicious** [comment] 2020-08-04 12:07
Hi @thvardhan, thanks for looking into this - yes, this is PHPStorm.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/16191979/89292036-8c23af80-d653-11ea-87c2-c2214a4ede49.png">

**Comment by thvardhan** [comment] 2020-08-05 12:27
Thanks, the issue is fixed in 4.2. it will be available on the market in a few days or alternatively, you can download it from github

**Closed as completed by thvardhan** 2020-08-05 12:27 UTC
Labels: bug
