### ISSUE TITLE
Updating the plugin forces IntelliJ theme change

### ISSUE THREAD

**Issue by ALDamico** [thvardhan/Gradianto#15] opened 2020-05-08 13:03 UTC
After an update to version 3.1.0, Gradianto reapplied the Midnight blue theme even though I was using Darcula at that time.

**Comment by thvardhan** [comment] 2020-05-08 13:19
This bug is not something caused by the plugin as I am only changing the color values nothing else is changed. It rather seems like an issue with IntelliJ that it reapplies the plugin after updates. The similar issue can be seen with other 3rd party plugins. 
you can open a bug ticket with IntelliJ https://youtrack.jetbrains.com/ and see if that works. I doubt there might already be a ticket for the IDE you are using. do check once.

**Comment by thvardhan** [comment] 2020-05-11 04:40
I've opened an issue for the same.
https://youtrack.jetbrains.com/issue/IDEA-240538

**Comment by thvardhan** [comment] 2020-05-19 07:28
The bug has been fixed by JetBrains and should come with the next version. Thanks to JetBrains!

**Closed as completed by thvardhan** 2020-05-19 07:28 UTC
Labels: Issue with IntelliJ
