### ISSUE TITLE
Diff view is not applying style and theme

### ISSUE THREAD

**Issue by cypherkaka** [thvardhan/Gradianto#1] opened 2019-05-17 17:12 UTC
Diff view is not applying theme on the original side.

![image](https://user-images.githubusercontent.com/1773799/57944586-73d84100-78a5-11e9-8cfa-656d13053a1e.png)

**Comment by thvardhan** [comment] 2019-05-17 17:25
I am unable to reproduce the issue. Can you help me by providing the steps and which IDE you are using along with the version?
I tried the same on WebStrom (as it seems you are using WebStrom)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17314986/57945139-b0805880-78f6-11e9-940a-aa8929f00b4e.png">
and it seems to be working fine.

**Comment by cypherkaka** [comment] 2019-05-17 17:31
Please see my settings below.

- IDE Details:   
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Subscription is active until May 2, 2020
JRE: 11.0.2+9-b159.44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I am using trying to compare JavaScript files.  

#Steps
1. Right click on .js file
2. Git > Compare with... > Select file revision

**Comment by thvardhan** [comment] 2019-05-17 17:59
Thank you for providing additional information. I am unable to find out how to fix this issue. I've installed a couple of other themes and apparently, all of them have the same issue so it might be an issue with the IntelliJ idea itself.

**Comment by thvardhan** [comment] 2019-05-17 18:03
I'll report the issue and get back to you

**Comment by thvardhan** [comment] 2019-05-17 18:16
You can also track this issue here : https://youtrack.jetbrains.com/issue/IDEA-214514

**Comment by thvardhan** [comment] 2023-09-15 17:43
Closing this issue due to not being related to the plugin.

**Closed as completed by thvardhan** 2023-09-15 17:43 UTC
Labels: Issue with IntelliJ
